---
collections: []

roles:
  - name: escapace.aws_cli
    src: https://github.com/escapace/ansible-aws_cli
    version: origin/trunk

  - name: escapace.escapace_releases
    src: https://github.com/escapace/ansible-escapace_releases
    version: origin/trunk
