name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: escapace/workflows/.github/workflows/ci-ansible-role.yaml@trunk
